### ISSUE TITLE
Faulty Contract Detection

### ISSUE THREAD

**Issue by RobertMCForster** [KadenZipfel/smart-contract-attack-vectors#8]
Some contracts do not want other contracts to interact with them (very common in gambling contracts using [sub-par RNG](https://github.com/KadenZipfel/smart-contract-attack-vectors/blob/master/attacks-and-vulnerabilites/weak-sources-randomness.md)). 

A common way to prevent this is to check whether the calling account has any code stored in it, however contract accounts initiating calls during their construction will not yet show that they store code.

An example of this is the FOMO3D bug.

**Comment by KadenZipfel** [comment]
I'm trying to find the FOMO3D bug you're mentioning but I'm only seeing the block stuffing DoS attack, are you sure it was FOMO3D?

**Comment by RobertMCForster** [comment]
https://www.reddit.com/r/ethereum/comments/916xni/how_to_pwn_fomo3d_a_beginners_guide/

**Comment by KadenZipfel** [comment]
Excellent, thank you!
